### ISSUE TITLE
After updating package it now doesn't work

### ISSUE THREAD

**Issue by LukeTim** [dhleong/ps4-waker#20] opened 2016-10-18 19:53 UTC
I am running Node 4.5 on a Raspberry Pi and recently updated all my npm packages and now find that ps4-waker is broken. It just returns an error about a missing bindings file

```
/usr/local/lib/node_modules/ps4-waker/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/ps4-waker/node_modules/ursa/build/ursaNative.node
 → /usr/local/lib/node_modules/ps4-waker/node_modules/ursa/build/Debug/ursaNative.node
 → /usr/local/lib/node_modules/ps4-waker/node_modules/ursa/build/Release/ursaNative.node
 → /usr/local/lib/node_modules/ps4-waker/node_modules/ursa/out/Debug/ursaNative.node
 → /usr/local/lib/node_modules/ps4-waker/node_modules/ursa/Debug/ursaNative.node
 → /usr/local/lib/node_modules/ps4-waker/node_modules/ursa/out/Release/ursaNative.node
 → /usr/local/lib/node_modules/ps4-waker/node_modules/ursa/Release/ursaNative.node
 → /usr/local/lib/node_modules/ps4-waker/node_modules/ursa/build/default/ursaNative.node
 → /usr/local/lib/node_modules/ps4-waker/node_modules/ursa/compiled/4.5.0/linux/arm/ursaNative.node
    at bindings (/usr/local/lib/node_modules/ps4-waker/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/ps4-waker/node_modules/ursa/lib/ursa.js:18:37)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ps4-waker/lib/ps4lib.js:3:12)
    at Module._compile (module.js:409:26)
```

**Comment by dhleong** [comment] 2016-10-18 23:51
This is probably #18. A PR is available but I'm not at home to test and release just now. Give me a week and should be able to fix this for you.

**Comment by LukeTim** [comment] 2016-10-20 08:45
@dhleong Okay, thanks!

**Comment by dhleong** [comment] 2016-10-22 12:40
Released version 1.0.1—please update and see if that fixes your issue.

**Comment by LukeTim** [comment] 2016-10-24 13:25
I am getting an error:

```
pi@homebridge:~ $ sudo ps4-waker
WAKEUP sent to device... 192.168.1.78
Logging in...
Done!
/usr/local/lib/node_modules/ps4-waker/lib/packets.js:107
        throw new Error("Cipher is not initialized!");
        ^

Error: Cipher is not initialized!
    at Packet.encrypted (/usr/local/lib/node_modules/ps4-waker/lib/packets.js:107:15)
    at Ps4Socket.login (/usr/local/lib/node_modules/ps4-waker/lib/ps4socket.js:246:6)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by dhleong** [comment] 2016-10-25 22:54
Odd, I can't reproduce that. Since you're running as sudo, I assume your `.ps4-wake.credentials.json` is in `/root`? Could you try the steps here:

https://github.com/dhleong/ps4-waker/issues/15#issuecomment-247224443

**Comment by beaumartinez** [comment] 2017-02-11 18:26
I get that error as well, I've created #31 to track it.

**Comment by dhleong** [comment] 2017-02-11 19:27
Since the original error seems to be resolved and a new ticket is filed for the cipher error, I'm going to close this one.

**Closed by dhleong** 2017-02-11 19:27 UTC
