### ISSUE TITLE
-d switch doesn't appear to work correctly with multiple PS4s on the network

### ISSUE THREAD

**Issue by Negan99** [dhleong/ps4-waker#13] opened 2016-07-10 16:48 UTC
I'm not sure whether I'm getting the syntax wrong but I've never been able to get the program to work correctly with 2 PS4s on my network.  I've eventually managed to register one at address 192.168.1.94 but the command line seems to ignore the address when I specify it.  Strangely when I search it normally only finds a single PS4 even though they are both sat in standy

pi@Raspberry01:~$ sudo ps4-waker standby -d 192.168.1.94
Unable to connect to PS4 at 192.168.1.73 { [Error: connect ECONNREFUSED 192.168.1.73:997]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.73',
  port: 997 }

Could there be an issue or have I done something wrong?

**Comment by dhleong** [comment] 2016-07-10 21:04
Ah, looks like there might be a bug there. I've only one device so haven't tested that code path thoroughly....

Try specifying a timeout, eg:

    ps4-waker standby -d 192.168.1.94 -t 10000

The timeout is in milliseconds

**Comment by dhleong** [comment] 2016-07-10 21:14
Note that this bug is probably caused by `standby` being newer than `search`, and because of this behavior:

```
Searching:
  If no timeout is provided to search, it will stop on the first result
```

**Comment by Negan99** [comment] 2016-07-10 22:23
Thanks - I had been thinking that I was doing something wrong.

Definitely strange results still

Searching when the PS4 was off
```
pi@Raspberry01:~$ sudo ps4-waker -d 192.168.1.94 -t 10000
[Error: undefined is already awake! (undefined)]
```

PS4 turned on manually but not detected
```
pi@Raspberry01:~$ sudo ps4-waker standby -d 192.168.1.94 -t 10000
Could not detect any PS4 device
```
Then this lot was ran immediately after the message above

```
pi@Raspberry01:~$ sudo ps4-waker
[Error: PS4-001 is already awake! (Ok)]
pi@Raspberry01:~$ sudo ps4-waker search
{ type: 'device',
  statusLine: '200 Ok',
  statusCode: '200',
  status: 'Ok',
  'host-id': 'XXXXXXXXXX',
  'host-type': 'PS4',
  'host-name': 'PS4-001',
  'host-request-port': '997',
  'device-discovery-protocol-version': '00020020',
  address: '192.168.1.94' }
pi@Raspberry01:~$ sudo ps4-waker search
{ type: 'device',
  statusLine: '620 Server Standby',
  statusCode: '620',
  status: 'Standby',
  'host-id': 'XXXXXXXXXX',
  'host-type': 'PS4',
  'host-name': 'PS4-811',
  'host-request-port': '997',
  'device-discovery-protocol-version': '00020020',
  address: '192.168.1.73' }

```

**Comment by dhleong** [comment] 2016-07-10 22:52
The first result (`[Error: undefined is already awake! (undefined)]`) is definitely bizarre. Not sure off hand what would cause that—will have to investigate. 

The second one is annoying but not atypical, depending on your router. The discovery process is best effort for both `ps4-waker` and the PS4 itself (communication is over UDP, if that means anything to you). You might try a timeout of ~5000 and a small retry loop if you need some reliability. 

The rest actually make sense:

1. Without any args, it finds the first PS4 to respond and tries to wake it up. It found the one you wanted, and it was indeed already awake
2. With just `search`, it prints out the response from the first PS4 to respond. In this case, it found the one you wanted, and the status is as expected (`200 Ok` means it's awake).
3. As with 2., but this time the other PS4 responded first

Try doing:

    ps4-waker search -t 10000

This is not documented (I'll add that when I fix the above-mentioned bug), but it should print the status of both PS4. The variant you tried (`standby -t 10000`) will just wait 10 seconds trying to find *any* PS4, and will *only* talk to the first one it finds. 

If you could try this with the PS4 in standby (the same state when you got the `undefined` response) and post the results, that could be helpful. The problem is [here](https://github.com/dhleong/ps4-waker/blob/master/index.js#L130). Since the status was `undefined`, then it's definitely not equal to `Standby`. *Probably*, we should treat `undefined` as "in standby," but I'd like to see what the rest of the response looked like. Not having the `status` is an unexpected state.... At least, though, it should be treated as "already awake."

Thanks for your help!

**Comment by Negan99** [comment] 2016-07-11 09:11
Tried several combinations but the 2nd PS4 is never found :(

`pi@Raspberry01:~$ ps4-waker search -t 50000
{ type: 'device',
  statusLine: '620 Server Standby',
  statusCode: '620',
  status: 'Standby',
  'host-id': 'XXXXX',
  'host-type': 'PS4',
  'host-name': 'PS4-811',
  'host-request-port': '997',
  'device-discovery-protocol-version': '00020020',
  address: '192.168.1.73' }
`
Thanks 
Steve

**Comment by dhleong** [comment] 2016-07-12 04:22
I believe I know what's going on. Now that #12 is taken care of, I'll try to put together a fix sometime in the next few days.

**Comment by dhleong** [comment] 2016-07-12 23:10
@Negan99 I just published version 0.9.0 to npm. Try updating and giving it a shot.

**Comment by Negan99** [comment] 2016-07-13 10:49
Many thanks - It's looking really good, will register the other PS4 at the weekend when I have time and make sure that all functions work on it too but search, wake and standby are all fine for the one that I had been working on previously.

Searching with the -t parameter stops after it finds the 1st PS4; not sure if this is now by design but in any case I use the -d switch to get the target that I want.

**Comment by dhleong** [comment] 2016-07-13 12:00
Woops! That was not intended. Search should only stop early if `-d` is provided. I've pushed 0.9.1 to fix that. 

Thanks for your help! I'm going to go ahead and close this ticket, but feel free to comment back here if you still encounter this issue over the weekend.

**Closed by dhleong** 2016-07-13 12:00 UTC
Labels: bug

**Comment by Negan99** [comment] 2016-07-13 13:21
Many thanks for the hard work that you've put in @dhleong 

I tried the bind to the other PS4 at lunchtime and got the following

`sudo ps4-waker -b -d 192.168.1.73 -t 5000
dns.js:114
    throw new TypeError('invalid arguments: ' +
    ^
TypeError: invalid arguments: hostname must be a string or falsey
    at Object.lookup (dns.js:114:11)
    at lookup (dgram.js:27:14)
    at UDP.lookup4 [as lookup] (dgram.js:32:10)
    at Socket.bind (dgram.js:170:16)
    at Waker.sendWake (/usr/lib/node_modules/ps4-waker/index.js:267:14)
    at /usr/lib/node_modules/ps4-waker/index.js:150:14
    at /usr/lib/node_modules/ps4-waker/index.js:178:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
`

Adjusting the syntax I had
`sudo ps4-waker -b 192.168.1.73 -t 5000
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: bind EADDRNOTAVAIL 192.168.1.73
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at dgram.js:214:18
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3`

Then finally
`sudo ps4-waker -b PS4-811
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: getaddrinfo EAI_AGAIN
    at Object.exports._errnoException (util.js:873:11)
    at errnoException (dns.js:32:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)` 

I don't actually need control of the 2nd PS4, reporting is sufficient but I thought I'd let you know just in case others might.  This was tested on 0.9.0.

**Comment by dhleong** [comment] 2016-07-13 13:31
-b is used when you have multiple network adapters. You probably just need
-d by itself to specify the other ps4

**Comment by dhleong** [comment] 2016-07-13 13:42
The description of `-b` was a bit confusing though, I admit. I've updated it to specify "network adapter IP" to contrast with `-d` which says "PS4 IP."
