### ISSUE TITLE
Remote Play App cannot find PS4-Waker

### ISSUE THREAD

**Issue by BenGmuN** [dhleong/ps4-waker#63] opened 2017-11-15 12:01 UTC
Be gentle - total programming n00b.

As the title suggests, I can't get my Remote Play app to 'find' the PS4-Waker. I'm attempting to run PS4-Waker using Windows command line (as it's all that's at my disposal). I have opened UDP ports 987 and 997 on my router, as well as 999 (which I've chosen at random and attempted to bind to), disabled Windows firewall, etc. all with no success. Tried via Android remote play app as well as Windows remote play app (installed on the same Windows system as PS4-waker itself).

Please help!

**Comment by BenGmuN** [comment] 2017-11-15 12:05
Also, the process I'm following is:
 - Physical PS4 is switched on
 - I run the PS4-waker (this tells me to launch the Playstation App and try to connect to PS4-Waker)
 - I open the Playstation App --> Settings --> Change PS4 to Connect to
Is there another way in which I should be trying to connect to the PS4-Waker?

Many thanks in advance.

**Comment by dhleong** [comment] 2017-11-15 12:32
Ah, the problem is you're using the wrong app ;) I haven't had to set this up in a while, but it seems Sony has split out the "second screen" feature from the main Playstation app. Give this one a try:

https://play.google.com/store/apps/details?id=com.playstation.mobile2ndscreen

**Comment by BenGmuN** [comment] 2017-11-15 12:51
Thank you so much for the speedy response! Unfortunately the 'Second Screen' app only finds my physical PS4 as well... In terms of the router, I have configured port forwarding rules for 987, 997 and (my random choice) 999 - I have set up separate forwarding rules for each, with the internal and external port numbers the same, forwarding on to my Windows PC running PS4-waker. Does that sound correct? Thanks again.

**Comment by dhleong** [comment] 2017-11-15 13:24
I just installed the new second screen app and tested locally—things still work for me, so must be a config issue on your end.

Have you followed everything here: https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#ps4-waker-cant-see-the-ps4 ?

How are you running `ps4-waker`, and what is it saying?

**Comment by dhleong** [comment] 2017-11-15 15:09
It looks like ps4-waker can see your PS4 just fine, it's just that the app
can't see ps4-waker.

Unfortunately I don't use Windows much myself, but on Linux systems, most
ports below 2000 ish need special privileges to listen to. You said you
disabled windows firewall, but it's possible windows is still blocking
those ports. You might try binding to a higher-numbered port, like 9001. In
your router configuration you should try forwarding port 997 (I think,
possibly it's 987) to 9001. You might also try running CMD as an
administrator.

**Comment by dhleong** [comment] 2017-12-04 13:28
Just tested without problems on a Windows machine, so this must be a router configuration issue. If you have any new information feel free to comment again, but I'm going to close this for now since it's been almost a month.

**Closed** 2017-12-04 13:28 UTC
Labels: invalid, question

**Comment by YSJP** [comment] 2019-02-02 05:48
Pls try this code on your pc.

>ps4-waker --pin [pincode]
